title: CS230 Deep Learning
email: ""
description: "Material for Stanford CS230"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cs230-stanford.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  cs230-stanford
google_analytics: UA-114319548-1


# Build settings
permalink: none
markdown: kramdown
theme: jekyll-theme-cayman
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
display-site-nav: false